# Build stage
FROM python:3.9-slim as build

# Create a virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code (local -> container)
COPY . .

# Production stage
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Create a non-root user for security
RUN adduser --disabled-password --no-create-home app

# Copy the virtual environment from the build stage
COPY --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Copy the application code from the build stage
COPY --from=build /app /app

# Set environment variables


# Switch to the non-root user
USER app

# Expose the port (just for documenting)
EXPOSE 8000

# Set the command to run the FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]